language: node_js

node_js: 
- "10.9.0"

jobs:
  include:
  - stage: Backend tests
    script: 
    - cd backend 
    - yarn 
    - yarn test:all_coverage
    after_script: yarn coveralls
  - stage: Frontend tests
    script:
    - cd frontend
    - yarn
    - yarn test:all_coverage
    after_script: yarn coveralls

