version: "3"
services:
  app:
    build:
      context: ./
      args:
        NANOCORP_FRONTEND_API_URL: /graphql
    image: "nanocorp_app"

    ports:
    - "8080:8080"
    networks:
    - dbnet
  db:
    build: ./db
    image: "nanocorp_db"
    networks:
    - dbnet
networks:
  dbnet:
