version: "3"
services:
  app:
    build:
      context: ./
      args:
        NANOCORP_FRONTEND_API_URL: /graphql
        NANOCORP_FRONTEND_CDN: /cdn/
    image: "nanocorp_app"
    environment:
    - NANOCORP_BACKEND_MONGO_URL=mongodb://db:27017
    ports:
    - "8080:8080"
    networks:
    - dbnet
    depends_on:
    - db
  db:
    build: ./db
    image: "nanocorp_db"
    networks:
    - dbnet
networks:
  dbnet:
